------------------------- [[ 语言相关 ]] ------------------------
local LOC = require("languages/loc")
local lang_id = LOC:GetLanguage()
local STRINGS = GLOBAL.STRINGS

-- 做语言区分 其实能用官方的最好用官方的
if lang_id == 22 or lang_id == 21 then
    -- 惊吓
    STRINGS.SKILLTREE.WENDY.WENDY_GHOSTCOMMAND_3_DESC = "阿比盖尔可以利用她作为幽灵的力量来惊吓。"

    -- 小惊吓
    STRINGS.SKILLTREE.WENDY.WENDY_SMALLGHOST_1 = "小惊吓的玩具会清晰的显示出来。"
    STRINGS.SKILLTREE.WENDY.WENDY_SMALLGHOST_2 = "有较小的概率会获得小惊吓的最后'感谢'。"
    STRINGS.SKILLTREE.WENDY.WENDY_SMALLGHOST_3 = "有稍大的概率会获得小惊吓的最后'感谢'。"

    -- 野餐盒
    STRINGS.SKILLTREE.WENDY.WENDY_POTION_CONTAINER_EXTRA_DESC = "同时也是存储料理的精致篮子。" 

    -- 额外产出
    STRINGS.SKILLTREE.WENDY.WENDY_POTION_YIELD_EXTRA_DESC = "阿比盖尔可以同时应用两种不同的普通药剂效果。\n"

    -- 骨灰罐线
    STRINGS.SKILLTREE.WENDY.WENDY_SISTURN_1 = "\n其中的花朵腐烂后会转变成哀悼荣耀。"
    STRINGS.SKILLTREE.WENDY.WENDY_SISTURN_2 = "\n阿比盖尔现在可以升到4级了。"
    STRINGS.SKILLTREE.WENDY.WENDY_SISTURN_3_DESC = "阿比盖尔会根据不同的花瓣获得不同的增益效果。"
    
    -- 位面线
    STRINGS.SKILLTREE.WENDY.WENDY_LUNAR_2_DESC_NEW = "阿比盖尔与月能调和，获得更多的位面防御。"
    STRINGS.SKILLTREE.WENDY.WENDY_LUNAR_3_DESC = "温蒂可以制作一种注入了月能的超级药剂，将转阿比盖尔转变成虚影状态，攻击方式同虚影一致。"
    STRINGS.SKILLTREE.WENDY.WENDY_SHADOW_2_DESC_NEW = "阿比盖尔与暗影调和，获得更多的位面防御。"
    STRINGS.SKILLTREE.WENDY.WENDY_SHADOW_3_DESC = "温蒂学会了制作暗影魔法药剂，阿比盖尔能够转变成黑暗魔法形态，协同温蒂可以对生物造成更多的位面伤害。"

    -- 发光浆果药剂
    STRINGS.NAMES.GHOSTLYELIXIR_LIGHT = "发光浆果药剂"
else
    -- 惊吓 
    STRINGS.SKILLTREE.WENDY.WENDY_GHOSTCOMMAND_3_DESC = "Abigail can use her powers as a spooky ghost to scare."

    -- Tiny Scare
    STRINGS.SKILLTREE.WENDY.WENDY_SMALLGHOST_1 = "The Pipspook's toy will manifest clearly."
    STRINGS.SKILLTREE.WENDY.WENDY_SMALLGHOST_2 = "Low chance to receive the final 'thanks' from Pipspook."
    STRINGS.SKILLTREE.WENDY.WENDY_SMALLGHOST_3 = "Slightly higher chance to receive the final 'thanks' from Pipspook."

    -- Picnic Basket
    STRINGS.SKILLTREE.WENDY.WENDY_POTION_CONTAINER_EXTRA_DESC = "An elegant basket for storing meals."

    -- extra yield
    STRINGS.SKILLTREE.WENDY.WENDY_POTION_YIELD_EXTRA_DESC = "Abigail can do apply elixer two different types of potions'buff at once.\n"

    -- Sisturn Line
    STRINGS.SKILLTREE.WENDY.WENDY_SISTURN_1 = "\nFlowers will transform into Mourning Glory when decayed."
    STRINGS.SKILLTREE.WENDY.WENDY_SISTURN_2 = "\nAbigail can now upgrade to level 4."
    STRINGS.SKILLTREE.WENDY.WENDY_SISTURN_3_DESC = "Abelibg can gain different buffs from different flowers."

    -- Planar Line
    STRINGS.SKILLTREE.WENDY.WENDY_LUNAR_2_DESC_NEW = "Abigail attunes with lunar energies and earns more Planar Defense."
    STRINGS.SKILLTREE.WENDY.WENDY_LUNAR_3_DESC = "Wendy can craft a super potion infused with lunar energy, transforming Abigail into an ethereal form with attacks identical to those of a phantom."
    STRINGS.SKILLTREE.WENDY.WENDY_SHADOW_2_DESC_NEW = "Abigail attunes with the shadows and earns more Planar Defense."
    STRINGS.SKILLTREE.WENDY.WENDY_SHADOW_3_DESC = "Wendy learns to craft shadow magic potions, enabling Abigail to transform into a dark magic form. When working in tandem with Wendy, they can deal additional planar damage to creatures."

    -- ghostlyelixir light
    STRINGS.NAMES.GHOSTLYELIXIR_LIGHT = STRINGS.NAMES.WORMLIGHT .." "..STRINGS.SCRAPBOOK.SUBCATS.ELIXER
end

-- 月数花 制作
STRINGS.RECIPE_DESC.WENDY_MOON_TREE_BLOSSOM = STRINGS.CHARACTERS.WOODIE.DESCRIBE.MOON_TREE_BLOSSOM
-- 发光浆果 制作
STRINGS.RECIPE_DESC.GHOSTLYELIXIR_LIGHT =STRINGS.RECIPE_DESC.CARNIVALCANNON_SPARKLE_KIT
-- 发光浆果 角色检查词
STRINGS.CHARACTERS.GENERIC.DESCRIBE.GHOSTLYELIXIR_LIGHT = STRINGS.CHARACTERS.WEBBER.DESCRIBE.WORMLIGHT

-- 小惊吓任务
-- 1
STRINGS.SKILLTREE.WENDY.WENDY_SMALLGHOST_1_DESC = STRINGS.SKILLTREE.WENDY.WENDY_SMALLGHOST_1_DESC .."\n"..STRINGS.SKILLTREE.WENDY.WENDY_SMALLGHOST_1 
-- 2
STRINGS.SKILLTREE.WENDY.WENDY_SMALLGHOST_2_DESC = STRINGS.SKILLTREE.WENDY.WENDY_SMALLGHOST_2_DESC .."\n"..STRINGS.SKILLTREE.WENDY.WENDY_SMALLGHOST_2
-- 3
STRINGS.SKILLTREE.WENDY.WENDY_SMALLGHOST_3_DESC = STRINGS.SKILLTREE.WENDY.WENDY_SMALLGHOST_3_DESC .."\n"..STRINGS.SKILLTREE.WENDY.WENDY_SMALLGHOST_3

-- 骨灰罐线
-- 1
STRINGS.SKILLTREE.WENDY.WENDY_SISTURN_1_DESC = STRINGS.SKILLTREE.WENDY.WENDY_SISTURN_1_DESC ..STRINGS.SKILLTREE.WENDY.WENDY_SISTURN_1
-- 2 四级阿比盖尔升级时的提示
STRINGS.CHARACTERS.WENDY.ANNOUNCE_GHOSTLYBOND_LEVELUP.LEVEL4 = STRINGS.CHARACTERS.WENDY.ANNOUNCE_SISTURN_FULL_BLOSSOM
STRINGS.CHARACTERS.WENDY.ANNOUNCE_ABIGAIL_SUMMON.LEVEL4 = STRINGS.CHARACTERS.WENDY.ANNOUNCE_ABIGAIL_SUMMON.LEVEL2
-- 二级骨灰罐 描述
STRINGS.SKILLTREE.WENDY.WENDY_SISTURN_2_DESC = STRINGS.SKILLTREE.WENDY.WENDY_SISTURN_2_DESC ..STRINGS.SKILLTREE.WENDY.WENDY_SISTURN_2

-- 指令线：
-- 逃离
STRINGS.SKILLTREE.WENDY.WENDY_GHOSTCOMMAND_1_TITLE = STRINGS.GHOSTCOMMANDS.ESCAPE
-- 攻击
STRINGS.SKILLTREE.WENDY.WENDY_GHOSTCOMMAND_2_TITLE = STRINGS.GHOSTCOMMANDS.ATTACK_AT
-- 惊吓
STRINGS.SKILLTREE.WENDY.WENDY_GHOSTCOMMAND_3_TITLE = STRINGS.GHOSTCOMMANDS.SCARE
-- 作祟
STRINGS.SKILLTREE.WENDY.WENDY_GHOSTCOMMAND_4_TITLE = STRINGS.GHOSTCOMMANDS.HAUNT_AT -- 作祟
STRINGS.SKILLTREE.WENDY.WENDY_GHOSTCOMMAND_4_DESC = STRINGS.SKILLTREE.WENDY.WENDY_GHOSTCOMMAND_HAUNT_DESC


-- 哀悼荣耀线
-- 幽魂花冠
STRINGS.SKILLTREE.WENDY.WENDY_GHOSTFLOWER_BUTTERFLY_TITLE = STRINGS.NAMES.GHOSTFLOWERHAT
-- 多年生植物祭坛
STRINGS.SKILLTREE.WENDY.WENDY_GHOSTFLOWER_HAT_TITLE = STRINGS.NAMES.WENDY_RESURRECTIONGRAVE
-- 野餐盒
STRINGS.SKILLTREE.WENDY.WENDY_POTION_CONTAINER_DESC = STRINGS.SKILLTREE.WENDY.WENDY_POTION_CONTAINER_DESC .."\n" ..STRINGS.SKILLTREE.WENDY.WENDY_POTION_CONTAINER_EXTRA_DESC 
-- 额外产出
STRINGS.SKILLTREE.WENDY.WENDY_POTION_YIELD_DESC = STRINGS.SKILLTREE.WENDY.WENDY_POTION_YIELD_EXTRA_DESC ..STRINGS.SKILLTREE.WENDY.WENDY_POTION_YIELD_DESC

-- 位面 相关
-- 月亮
-- STRINGS.SKILLTREE.WENDY.WENDY_LUNAR_1_TITLE = STRINGS.SKILLTREE.WILSON.WILSON_ALLEGIANCE_LUNAR_TITLE .."I"
-- STRINGS.SKILLTREE.WENDY.WENDY_LUNAR_2_TITLE = STRINGS.SKILLTREE.WILSON.WILSON_ALLEGIANCE_LUNAR_TITLE .."II"
STRINGS.SKILLTREE.WENDY.WENDY_LUNAR_2_DESC  = STRINGS.SKILLTREE.WENDY.WENDY_LUNAR_2_DESC_NEW

-- STRINGS.SKILLTREE.WENDY.WENDY_SHADOW_1_TITLE = STRINGS.SKILLTREE.WILSON.WILSON_ALLEGIANCE_SHADOW_TITLE .."I"
-- STRINGS.SKILLTREE.WENDY.WENDY_SHADOW_2_TITLE = STRINGS.SKILLTREE.WILSON.WILSON_ALLEGIANCE_SHADOW_TITLE .."II"
STRINGS.SKILLTREE.WENDY.WENDY_SHADOW_2_DESC  = STRINGS.SKILLTREE.WENDY.WENDY_SHADOW_2_DESC_NEW

-- STRINGS.SKILLTREE.WENDY.WENDY_LUNAR_3_TITLE = STRINGS.SKILLTREE.WENDY.WENDY_LUNAR_2_TITLE
-- STRINGS.SKILLTREE.WENDY.WENDY_LUNAR_2_TITLE = STRINGS.SKILLTREE.WENDY.WENDY_LUNAR_1_TITLE
-- 暗影
-- STRINGS.SKILLTREE.WENDY.WENDY_SHADOW_3_TITLE = STRINGS.SKILLTREE.WENDY.WENDY_SHADOW_2_TITLE
-- STRINGS.SKILLTREE.WENDY.WENDY_SHADOW_2_TITLE = STRINGS.SKILLTREE.WENDY.WENDY_SHADOW_1_TITLE
-- STRINGS.SKILLTREE.WENDY.WENDY_SHADOW_1_TITLE = STRINGS.SKILLTREE.WILSON.WILSON_ALLEGIANCE_SHADOW_TITLE